language: python

addons:
    apt:
      packages:
        - xvfb
        - herbstluftwm
env:
   global:
      - OFFICIAL_REPO="pcdshub/lucid"
matrix: 
  include:
     - python: 3.6
       env: BUILD_DOCS=1

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build
  - conda config --add channels pcds-tag
  - conda config --append channels conda-forge
  # Useful for debugging any issues with conda
  - conda info -a
  # Test conda build
  #- conda build -q conda-recipe --python $TRAVIS_PYTHON_VERSION --output-folder bld-dir
  #- conda config --add channels "file://`pwd`/bld-dir"
  #Grab all dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip pyqt=5 --file dev-requirements.txt
  #Launch Conda environment
  - source activate test-environment
  # Install the rest of the dependencies that are not in CONDA or PyPI. This will
  # hopefully be removed when qtpydocking is available on CONDA 
  - pip install -Ur requirements.txt
  - python setup.py install

before_script:
    #Taken from docs.travis-ci.com/user/gui-and-headless-browsers
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3 # give xvfb some time to start
  # Run windows manager
  - "herbstluftwm &"
  - sleep 1

script:
  - coverage run run_tests.py
  - coverage report -m
  - flake8 lucid 
  - set -e

after_success:
  - codecov
