{% set data = load_setup_py_data() %}

package:
  name: lucid
  version : {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python {{PY_VER}}*,>=3
    - setuptools

  run:
    - python {{PY_VER}}*,>=3
    - pydm
    - pyqtads
    - ophyd
    - qtpy
    - typhon >=0.4

test:
  imports:
    - lucid

about:
  home: https://github.com/pcdshub/lucid
  license: SLAC Open License
  summary: LCLS User Control and Interface Design
